### ISSUE TITLE
Need a "Quick Start" document at the top level

### ISSUE THREAD

**Issue by znmeb** [hackoregon/transportation-systems-docker#16]
Assume I've 

1. Connected to the internet
2. Installed Docker hosting
3. Cloned this repository
4. Opened a terminal and typed `cd transportation-systems-docker`.

Now what? Do I need to check out a branch? What environment variables do I need to set? Do I type `docker-compose -f <something> up -d`?

**Comment by bhgrant8** [comment]
added to main readme
