### ISSUE TITLE
Test GeoDjango Image

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/transportation-systems-docker#6]
Need to test geodjango integrations and spatial libraries are installing correctly within the container

**Comment by bhgrant8** [comment]
I was successfully able to run through the geodjango tutorial in an interactive shell within the container:

https://docs.djangoproject.com/en/2.0/ref/contrib/gis/tutorial/

This should satisfy this requirement.

**Comment by znmeb** [comment]
OK - I'll try to reproduce it tomorrow on Windows!
